### ISSUE TITLE
User 鉴权的处理

### ISSUE THREAD

**Issue by csvwolf** [go-kratos/beer-shop#3]
没有找到 CreateOrder 上对于 user 的处理，但是 Login 返回的是 token，是准备用 token 来处理鉴权吗，那每个 rpc 都要接收 token 吗

**Comment by Casper-Mars** [comment]
You can find it under this place
https://github.com/go-kratos/beer-shop/blob/a29eae57a9baeae9969e9a7d418ff677cf494a21/app/shop/interface/internal/server/http.go#L41
