### ISSUE TITLE
how can i deploy this project on local machine

### ISSUE THREAD

**Issue by cesc1802** [go-kratos/beer-shop#9]

**Comment by Windfarer** [comment]
This project is not finished yet, maybe cannot be fully deployed, you can run every single service with `kratos run` command.

**Comment by cesc1802** [comment]
Thanks. But i nees it to try tour framework in production. Please process it soon

**Comment by Windfarer** [comment]
If you need some runnable examples, please take a look at https://github.com/go-kratos/kratos/tree/main/examples
